# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 16:59
from __future__ import unicode_literals

import common.arrayfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=b'slug')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[(b'D', b'Not Reviewed'), (b'P', b'Published'), (b'E', b'Expired')], default=b'D', max_length=1)),
                ('views', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(auto_now=True, help_text=b'Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=b'slug')),
                ('description', models.TextField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('path', common.arrayfields.IntegerArrayField(blank=True, editable=False)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='blog.Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=b'slug')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name=b'the related category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='keyword_set', to='blog.Tag', verbose_name=b'the related tags'),
        ),
    ]
